"""
Stage 2 Distillation Tensor Preparer v2
========================================
v2 of prepare_distillation_tensors.py — replaces the exact inner join with a
two-tier Heuristic Fallback Matcher to recover scans that MZmine re-numbered
between the JSON export and the raw mzML.

Tier 1  — exact scan_number join (same as v1)
Tier 2  — RT proximity (±0.1 min) + precursor_mz proximity (±10 ppm)
          Only attempted when the Stage 1 parquet contains an `rt_minutes`
          column (produced by tensorizer_v2.py).  If the column is absent
          (e.g. Stage 1 was generated by the legacy tensorizer), Stage 2 v2
          silently falls back to Tier 1 only and prints a notice.

Input:
  --spectra      path to one clean_spectra_*.parquet (Stage 1 v2 output)
  --index        path to master_metadata_index_v2.parquet (Stage 0 v2 output)
  --outdir       directory for output distillation_tensors_v2_*.parquet

Output schema (same columns as v1 for training-loop compatibility):
  intact_parent_smiles  str    — SMILES of intact parent molecule
  ms2_precursor_mz      float  — MS2 precursor m/z (from Stage 1 spectra)
  collision_energy      str    — collision energy string
  ms3_mz                list   — pruned/thresholded m/z array
  ms3_intensity         list   — sqrt-normalised intensity array
"""

from __future__ import annotations

import argparse
import os
import sys

import pandas as pd
import pyarrow.parquet as pq


# ── Heuristic Fallback Matcher ────────────────────────────────────────────────

def heuristic_json_merge(
    spectra_df: pd.DataFrame,
    file_index: pd.DataFrame,
) -> pd.DataFrame:
    """
    Two-tier merge of Stage 1 spectra against a v2 master index slice.

    Tier 1: exact scan_number join.
    Tier 2: RT ±0.1 min AND precursor_mz ±10 ppm (only when rt_minutes present).
    """
    # --- Tier 1 ---
    tier1 = pd.merge(spectra_df, file_index, on="scan_number", how="inner")

    has_rt = "rt_minutes" in spectra_df.columns
    if not has_rt:
        print(f"    [v2] rt_minutes absent — Tier 1 only ({len(tier1)} matches)")
        return tier1

    print(f"    [v2] Tier 1: {len(tier1)} exact matches.")

    # Rows in spectra_df that didn't match in Tier 1
    matched_scans = set(tier1["scan_number"])
    unmatched = spectra_df[~spectra_df["scan_number"].isin(matched_scans)].copy()

    if unmatched.empty:
        return tier1

    print(f"    [v2] Tier 2 candidate pool: {len(unmatched)} unmatched spectra rows.")

    # --- Tier 2: RT + precursor_mz proximity ---
    tier2_records: list[dict] = []

    for _, row in unmatched.iterrows():
        rt  = row["rt_minutes"]
        mz  = row["ms2_precursor_mz"]

        # RT window ±0.1 min
        rt_mask    = (file_index["rt"] - rt).abs() <= 0.1
        candidates = file_index[rt_mask]
        if candidates.empty:
            continue

        # precursor_mz window ±10 ppm
        ppm_err    = (candidates["precursor_mz"] - mz).abs() / mz * 1e6
        candidates = candidates[ppm_err <= 10.0]
        if candidates.empty:
            continue

        # Closest RT neighbour wins
        best_idx = (candidates["rt"] - rt).abs().idxmin()
        best     = candidates.loc[best_idx]

        # Spectra columns take priority for conflicts (preserves original scan_number)
        merged = {**best.to_dict(), **row.to_dict()}
        tier2_records.append(merged)

    if not tier2_records:
        print("    [v2] Tier 2: 0 additional matches.")
        return tier1

    tier2    = pd.DataFrame(tier2_records)
    combined = pd.concat([tier1, tier2], ignore_index=True)
    combined = combined.drop_duplicates(subset=["scan_number"])

    print(f"    [v2] Tier 2: {len(tier2)} additional matches. "
          f"Combined: {len(combined)} rows.")
    return combined


# ── File-level processor ──────────────────────────────────────────────────────

def prepare_tensors_v2(
    clean_spectra_path: str,
    master_index_path: str,
    out_dir: str,
) -> None:
    spectra_df = pd.read_parquet(clean_spectra_path)

    base_file  = (
        os.path.basename(clean_spectra_path)
        .replace("clean_spectra_", "")
        .replace(".parquet", ".mzML")
    )
    # Predicate pushdown: read only rows for this mzML file (avoids loading
    # the full 3.29M-row index into each worker process).
    file_index = pq.read_table(
        master_index_path,
        filters=[("mzml_file", "=", base_file)],
    ).to_pandas()

    if file_index.empty:
        print(f"  Warning: No metadata found for {base_file}. Skipping.")
        return

    print(f"  Processing {base_file} — "
          f"{len(spectra_df)} spectra rows, {len(file_index)} index rows.")

    merged_df = heuristic_json_merge(spectra_df, file_index)

    if merged_df.empty:
        print(f"  No rows survived merge for {base_file}.")
        return

    final_df = merged_df[[
        "smiles",
        "ms2_precursor_mz",
        "collision_energy",
        "ms3_mz",
        "ms3_intensity",
    ]].rename(columns={"smiles": "intact_parent_smiles"})

    out_name = (
        os.path.basename(clean_spectra_path)
        .replace("clean_spectra_", "distillation_tensors_v2_")
    )
    out_path = os.path.join(out_dir, out_name)
    os.makedirs(out_dir, exist_ok=True)
    final_df.to_parquet(out_path, index=False, engine="pyarrow")
    print(f"  Merged {len(final_df)} tensors -> {out_name}")


# Backwards-compatible alias
prepare_tensors = prepare_tensors_v2


# ── CLI ───────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Stage 2 v2 Distillation Tensor Preparer")
    parser.add_argument("--spectra", required=True,
                        help="Path to clean_spectra_*.parquet (Stage 1 output)")
    parser.add_argument("--index",   required=True,
                        help="Path to master_metadata_index_v2.parquet")
    parser.add_argument("--outdir",  required=True,
                        help="Output directory for distillation_tensors_v2_*.parquet")
    args = parser.parse_args()
    prepare_tensors_v2(args.spectra, args.index, args.outdir)
