apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ms-pred-softlabel-pvc
  namespace: wang-bioinf
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: rook-cephfs
  resources:
    requests:
      storage: 20Gi
